// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getGameGamesAppIdGet, getProfileRecommendationsRecommendProfilePost, getRecommendationsRecommendGet, type Options, searchGamesGamesSearchGet } from '../sdk.gen';
import type { GetGameGamesAppIdGetData, GetGameGamesAppIdGetError, GetGameGamesAppIdGetResponse, GetProfileRecommendationsRecommendProfilePostData, GetProfileRecommendationsRecommendProfilePostError, GetProfileRecommendationsRecommendProfilePostResponse, GetRecommendationsRecommendGetData, GetRecommendationsRecommendGetError, GetRecommendationsRecommendGetResponse, SearchGamesGamesSearchGetData, SearchGamesGamesSearchGetError, SearchGamesGamesSearchGetResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const searchGamesGamesSearchGetQueryKey = (options: Options<SearchGamesGamesSearchGetData>) => createQueryKey('searchGamesGamesSearchGet', options);

/**
 * Search Games
 *
 * Search games by name.
 */
export const searchGamesGamesSearchGetOptions = (options: Options<SearchGamesGamesSearchGetData>) => queryOptions<SearchGamesGamesSearchGetResponse, SearchGamesGamesSearchGetError, SearchGamesGamesSearchGetResponse, ReturnType<typeof searchGamesGamesSearchGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await searchGamesGamesSearchGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: searchGamesGamesSearchGetQueryKey(options)
});

export const getGameGamesAppIdGetQueryKey = (options: Options<GetGameGamesAppIdGetData>) => createQueryKey('getGameGamesAppIdGet', options);

/**
 * Get Game
 *
 * Get full details for a single game.
 */
export const getGameGamesAppIdGetOptions = (options: Options<GetGameGamesAppIdGetData>) => queryOptions<GetGameGamesAppIdGetResponse, GetGameGamesAppIdGetError, GetGameGamesAppIdGetResponse, ReturnType<typeof getGameGamesAppIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGameGamesAppIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGameGamesAppIdGetQueryKey(options)
});

export const getRecommendationsRecommendGetQueryKey = (options: Options<GetRecommendationsRecommendGetData>) => createQueryKey('getRecommendationsRecommendGet', options);

/**
 * Get Recommendations
 *
 * Get similar game recommendations based on content similarity and review quality.
 */
export const getRecommendationsRecommendGetOptions = (options: Options<GetRecommendationsRecommendGetData>) => queryOptions<GetRecommendationsRecommendGetResponse, GetRecommendationsRecommendGetError, GetRecommendationsRecommendGetResponse, ReturnType<typeof getRecommendationsRecommendGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRecommendationsRecommendGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRecommendationsRecommendGetQueryKey(options)
});

/**
 * Get Profile Recommendations
 *
 * Get recommendations based on a user profile.
 */
export const getProfileRecommendationsRecommendProfilePostMutation = (options?: Partial<Options<GetProfileRecommendationsRecommendProfilePostData>>): UseMutationOptions<GetProfileRecommendationsRecommendProfilePostResponse, GetProfileRecommendationsRecommendProfilePostError, Options<GetProfileRecommendationsRecommendProfilePostData>> => {
    const mutationOptions: UseMutationOptions<GetProfileRecommendationsRecommendProfilePostResponse, GetProfileRecommendationsRecommendProfilePostError, Options<GetProfileRecommendationsRecommendProfilePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await getProfileRecommendationsRecommendProfilePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
