// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getGameGamesAppIdGet, getLibrarySteamLibrarySteamIdGet, getProfileRecommendationsRecommendProfilePost, getRecommendationsRecommendGet, healthCheckHealthGet, type Options, searchGamesByTagsGamesByTagsGet, searchGamesGamesSearchGet, searchTagsGamesTagsGet } from '../sdk.gen';
import type { GetGameGamesAppIdGetData, GetGameGamesAppIdGetError, GetGameGamesAppIdGetResponse, GetLibrarySteamLibrarySteamIdGetData, GetLibrarySteamLibrarySteamIdGetError, GetLibrarySteamLibrarySteamIdGetResponse, GetProfileRecommendationsRecommendProfilePostData, GetProfileRecommendationsRecommendProfilePostError, GetProfileRecommendationsRecommendProfilePostResponse, GetRecommendationsRecommendGetData, GetRecommendationsRecommendGetError, GetRecommendationsRecommendGetResponse, HealthCheckHealthGetData, SearchGamesByTagsGamesByTagsGetData, SearchGamesByTagsGamesByTagsGetError, SearchGamesByTagsGamesByTagsGetResponse, SearchGamesGamesSearchGetData, SearchGamesGamesSearchGetError, SearchGamesGamesSearchGetResponse, SearchTagsGamesTagsGetData, SearchTagsGamesTagsGetError, SearchTagsGamesTagsGetResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const searchGamesGamesSearchGetQueryKey = (options: Options<SearchGamesGamesSearchGetData>) => createQueryKey('searchGamesGamesSearchGet', options);

/**
 * Search Games
 *
 * Search games by name.
 */
export const searchGamesGamesSearchGetOptions = (options: Options<SearchGamesGamesSearchGetData>) => queryOptions<SearchGamesGamesSearchGetResponse, SearchGamesGamesSearchGetError, SearchGamesGamesSearchGetResponse, ReturnType<typeof searchGamesGamesSearchGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await searchGamesGamesSearchGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: searchGamesGamesSearchGetQueryKey(options)
});

export const searchTagsGamesTagsGetQueryKey = (options: Options<SearchTagsGamesTagsGetData>) => createQueryKey('searchTagsGamesTagsGet', options);

/**
 * Search Tags
 *
 * Search tags by name.
 */
export const searchTagsGamesTagsGetOptions = (options: Options<SearchTagsGamesTagsGetData>) => queryOptions<SearchTagsGamesTagsGetResponse, SearchTagsGamesTagsGetError, SearchTagsGamesTagsGetResponse, ReturnType<typeof searchTagsGamesTagsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await searchTagsGamesTagsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: searchTagsGamesTagsGetQueryKey(options)
});

export const searchGamesByTagsGamesByTagsGetQueryKey = (options: Options<SearchGamesByTagsGamesByTagsGetData>) => createQueryKey('searchGamesByTagsGamesByTagsGet', options);

/**
 * Search Games By Tags
 *
 * Search games by tags (AND logic — games must have all selected tags).
 */
export const searchGamesByTagsGamesByTagsGetOptions = (options: Options<SearchGamesByTagsGamesByTagsGetData>) => queryOptions<SearchGamesByTagsGamesByTagsGetResponse, SearchGamesByTagsGamesByTagsGetError, SearchGamesByTagsGamesByTagsGetResponse, ReturnType<typeof searchGamesByTagsGamesByTagsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await searchGamesByTagsGamesByTagsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: searchGamesByTagsGamesByTagsGetQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const searchGamesByTagsGamesByTagsGetInfiniteQueryKey = (options: Options<SearchGamesByTagsGamesByTagsGetData>): QueryKey<Options<SearchGamesByTagsGamesByTagsGetData>> => createQueryKey('searchGamesByTagsGamesByTagsGet', options, true);

/**
 * Search Games By Tags
 *
 * Search games by tags (AND logic — games must have all selected tags).
 */
export const searchGamesByTagsGamesByTagsGetInfiniteOptions = (options: Options<SearchGamesByTagsGamesByTagsGetData>) => infiniteQueryOptions<SearchGamesByTagsGamesByTagsGetResponse, SearchGamesByTagsGamesByTagsGetError, InfiniteData<SearchGamesByTagsGamesByTagsGetResponse>, QueryKey<Options<SearchGamesByTagsGamesByTagsGetData>>, number | Pick<QueryKey<Options<SearchGamesByTagsGamesByTagsGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<SearchGamesByTagsGamesByTagsGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await searchGamesByTagsGamesByTagsGet({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: searchGamesByTagsGamesByTagsGetInfiniteQueryKey(options)
});

export const getGameGamesAppIdGetQueryKey = (options: Options<GetGameGamesAppIdGetData>) => createQueryKey('getGameGamesAppIdGet', options);

/**
 * Get Game
 *
 * Get full details for a single game.
 */
export const getGameGamesAppIdGetOptions = (options: Options<GetGameGamesAppIdGetData>) => queryOptions<GetGameGamesAppIdGetResponse, GetGameGamesAppIdGetError, GetGameGamesAppIdGetResponse, ReturnType<typeof getGameGamesAppIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGameGamesAppIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGameGamesAppIdGetQueryKey(options)
});

export const getRecommendationsRecommendGetQueryKey = (options: Options<GetRecommendationsRecommendGetData>) => createQueryKey('getRecommendationsRecommendGet', options);

/**
 * Get Recommendations
 *
 * Get similar game recommendations based on content similarity and review quality.
 */
export const getRecommendationsRecommendGetOptions = (options: Options<GetRecommendationsRecommendGetData>) => queryOptions<GetRecommendationsRecommendGetResponse, GetRecommendationsRecommendGetError, GetRecommendationsRecommendGetResponse, ReturnType<typeof getRecommendationsRecommendGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRecommendationsRecommendGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRecommendationsRecommendGetQueryKey(options)
});

/**
 * Get Profile Recommendations
 *
 * Get recommendations based on a user profile.
 */
export const getProfileRecommendationsRecommendProfilePostMutation = (options?: Partial<Options<GetProfileRecommendationsRecommendProfilePostData>>): UseMutationOptions<GetProfileRecommendationsRecommendProfilePostResponse, GetProfileRecommendationsRecommendProfilePostError, Options<GetProfileRecommendationsRecommendProfilePostData>> => {
    const mutationOptions: UseMutationOptions<GetProfileRecommendationsRecommendProfilePostResponse, GetProfileRecommendationsRecommendProfilePostError, Options<GetProfileRecommendationsRecommendProfilePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await getProfileRecommendationsRecommendProfilePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getLibrarySteamLibrarySteamIdGetQueryKey = (options: Options<GetLibrarySteamLibrarySteamIdGetData>) => createQueryKey('getLibrarySteamLibrarySteamIdGet', options);

/**
 * Get Library
 *
 * Get all games in a user's library that has more than 0 hours playtime.
 */
export const getLibrarySteamLibrarySteamIdGetOptions = (options: Options<GetLibrarySteamLibrarySteamIdGetData>) => queryOptions<GetLibrarySteamLibrarySteamIdGetResponse, GetLibrarySteamLibrarySteamIdGetError, GetLibrarySteamLibrarySteamIdGetResponse, ReturnType<typeof getLibrarySteamLibrarySteamIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getLibrarySteamLibrarySteamIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getLibrarySteamLibrarySteamIdGetQueryKey(options)
});

export const healthCheckHealthGetQueryKey = (options?: Options<HealthCheckHealthGetData>) => createQueryKey('healthCheckHealthGet', options);

/**
 * Health Check
 */
export const healthCheckHealthGetOptions = (options?: Options<HealthCheckHealthGetData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof healthCheckHealthGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthCheckHealthGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthCheckHealthGetQueryKey(options)
});
