// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetGameGamesGameIdGetData, GetGameGamesGameIdGetErrors, GetGameGamesGameIdGetResponses, GetRecommendationsRecommendGetData, GetRecommendationsRecommendGetErrors, GetRecommendationsRecommendGetResponses, SearchGamesGamesSearchGetData, SearchGamesGamesSearchGetErrors, SearchGamesGamesSearchGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Search Games
 *
 * Search games by name prefix.
 */
export const searchGamesGamesSearchGet = <ThrowOnError extends boolean = false>(options: Options<SearchGamesGamesSearchGetData, ThrowOnError>) => (options.client ?? client).get<SearchGamesGamesSearchGetResponses, SearchGamesGamesSearchGetErrors, ThrowOnError>({ url: '/games/search', ...options });

/**
 * Get Game
 *
 * Get full details for a single game.
 */
export const getGameGamesGameIdGet = <ThrowOnError extends boolean = false>(options: Options<GetGameGamesGameIdGetData, ThrowOnError>) => (options.client ?? client).get<GetGameGamesGameIdGetResponses, GetGameGamesGameIdGetErrors, ThrowOnError>({ url: '/games/{game_id}', ...options });

/**
 * Get Recommendations
 *
 * Get similar game recommendations based on content similarity and review quality.
 */
export const getRecommendationsRecommendGet = <ThrowOnError extends boolean = false>(options: Options<GetRecommendationsRecommendGetData, ThrowOnError>) => (options.client ?? client).get<GetRecommendationsRecommendGetResponses, GetRecommendationsRecommendGetErrors, ThrowOnError>({ url: '/recommend', ...options });
