// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetGameGamesAppIdGetData, GetGameGamesAppIdGetErrors, GetGameGamesAppIdGetResponses, GetLibrarySteamLibrarySteamIdGetData, GetLibrarySteamLibrarySteamIdGetErrors, GetLibrarySteamLibrarySteamIdGetResponses, GetProfileRecommendationsRecommendProfilePostData, GetProfileRecommendationsRecommendProfilePostErrors, GetProfileRecommendationsRecommendProfilePostResponses, GetRecommendationsRecommendGetData, GetRecommendationsRecommendGetErrors, GetRecommendationsRecommendGetResponses, HealthCheckHealthGetData, HealthCheckHealthGetResponses, SearchGamesByTagsGamesByTagsGetData, SearchGamesByTagsGamesByTagsGetErrors, SearchGamesByTagsGamesByTagsGetResponses, SearchGamesGamesSearchGetData, SearchGamesGamesSearchGetErrors, SearchGamesGamesSearchGetResponses, SearchTagsGamesTagsGetData, SearchTagsGamesTagsGetErrors, SearchTagsGamesTagsGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Search Games
 *
 * Search games by name.
 */
export const searchGamesGamesSearchGet = <ThrowOnError extends boolean = false>(options: Options<SearchGamesGamesSearchGetData, ThrowOnError>) => (options.client ?? client).get<SearchGamesGamesSearchGetResponses, SearchGamesGamesSearchGetErrors, ThrowOnError>({ url: '/games/search', ...options });

/**
 * Search Tags
 *
 * Search tags by name.
 */
export const searchTagsGamesTagsGet = <ThrowOnError extends boolean = false>(options: Options<SearchTagsGamesTagsGetData, ThrowOnError>) => (options.client ?? client).get<SearchTagsGamesTagsGetResponses, SearchTagsGamesTagsGetErrors, ThrowOnError>({ url: '/games/tags', ...options });

/**
 * Search Games By Tags
 *
 * Search games by tags (AND logic — games must have all selected tags).
 */
export const searchGamesByTagsGamesByTagsGet = <ThrowOnError extends boolean = false>(options: Options<SearchGamesByTagsGamesByTagsGetData, ThrowOnError>) => (options.client ?? client).get<SearchGamesByTagsGamesByTagsGetResponses, SearchGamesByTagsGamesByTagsGetErrors, ThrowOnError>({ url: '/games/by-tags', ...options });

/**
 * Get Game
 *
 * Get full details for a single game.
 */
export const getGameGamesAppIdGet = <ThrowOnError extends boolean = false>(options: Options<GetGameGamesAppIdGetData, ThrowOnError>) => (options.client ?? client).get<GetGameGamesAppIdGetResponses, GetGameGamesAppIdGetErrors, ThrowOnError>({ url: '/games/{app_id}', ...options });

/**
 * Get Recommendations
 *
 * Get similar game recommendations based on content similarity and review quality.
 */
export const getRecommendationsRecommendGet = <ThrowOnError extends boolean = false>(options: Options<GetRecommendationsRecommendGetData, ThrowOnError>) => (options.client ?? client).get<GetRecommendationsRecommendGetResponses, GetRecommendationsRecommendGetErrors, ThrowOnError>({ url: '/recommend', ...options });

/**
 * Get Profile Recommendations
 *
 * Get recommendations based on a user profile.
 */
export const getProfileRecommendationsRecommendProfilePost = <ThrowOnError extends boolean = false>(options: Options<GetProfileRecommendationsRecommendProfilePostData, ThrowOnError>) => (options.client ?? client).post<GetProfileRecommendationsRecommendProfilePostResponses, GetProfileRecommendationsRecommendProfilePostErrors, ThrowOnError>({
    url: '/recommend/profile',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Library
 *
 * Get all games in a user's library that has more than 0 hours playtime.
 */
export const getLibrarySteamLibrarySteamIdGet = <ThrowOnError extends boolean = false>(options: Options<GetLibrarySteamLibrarySteamIdGetData, ThrowOnError>) => (options.client ?? client).get<GetLibrarySteamLibrarySteamIdGetResponses, GetLibrarySteamLibrarySteamIdGetErrors, ThrowOnError>({ url: '/steam/library/{steam_id}', ...options });

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
