// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * GameDetail
 *
 * Full game detail for /games/{id}.
 */
export type GameDetail = {
    /**
     * Id
     */
    id: number;
    /**
     * Game Name
     */
    game_name: string;
    /**
     * Header Image
     */
    header_image: string;
    /**
     * Short Description
     */
    short_description: string;
    /**
     * Genres
     */
    genres: Array<string>;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Screenshots
     */
    screenshots: Array<string>;
    /**
     * Wilson Score
     */
    wilson_score: number;
};

/**
 * GameRecommendation
 *
 * A single recommended game.
 */
export type GameRecommendation = {
    /**
     * Id
     */
    id: number;
    /**
     * Game Name
     */
    game_name: string;
    /**
     * Header Image
     */
    header_image: string;
    /**
     * Similarity
     */
    similarity: number;
    /**
     * Wilson Score
     */
    wilson_score: number;
    /**
     * Hybrid Score
     */
    hybrid_score: number;
};

/**
 * GameSearchResult
 *
 * Search result.
 */
export type GameSearchResult = {
    /**
     * Game Name
     */
    game_name: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * RecommendationResponse
 *
 * Response wrapper for the /recommend endpoint.
 */
export type RecommendationResponse = {
    /**
     * Target Game
     */
    target_game: string;
    /**
     * Recommendations
     */
    recommendations: Array<GameRecommendation>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type SearchGamesGamesSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         *
         * Search prefix
         */
        q: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/games/search';
};

export type SearchGamesGamesSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchGamesGamesSearchGetError = SearchGamesGamesSearchGetErrors[keyof SearchGamesGamesSearchGetErrors];

export type SearchGamesGamesSearchGetResponses = {
    /**
     * Response Search Games Games Search Get
     *
     * Successful Response
     */
    200: Array<GameSearchResult>;
};

export type SearchGamesGamesSearchGetResponse = SearchGamesGamesSearchGetResponses[keyof SearchGamesGamesSearchGetResponses];

export type GetGameGamesGameIdGetData = {
    body?: never;
    path: {
        /**
         * Game Id
         */
        game_id: number;
    };
    query?: never;
    url: '/games/{game_id}';
};

export type GetGameGamesGameIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGameGamesGameIdGetError = GetGameGamesGameIdGetErrors[keyof GetGameGamesGameIdGetErrors];

export type GetGameGamesGameIdGetResponses = {
    /**
     * Successful Response
     */
    200: GameDetail;
};

export type GetGameGamesGameIdGetResponse = GetGameGamesGameIdGetResponses[keyof GetGameGamesGameIdGetResponses];

export type GetRecommendationsRecommendGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Game
         *
         * Name of the game to find recommendations for
         */
        game: string;
        /**
         * Top N
         *
         * Number of recommendations
         */
        top_n?: number;
        /**
         * Quality Power
         *
         * Quality weight exponent
         */
        quality_power?: number;
    };
    url: '/recommend';
};

export type GetRecommendationsRecommendGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRecommendationsRecommendGetError = GetRecommendationsRecommendGetErrors[keyof GetRecommendationsRecommendGetErrors];

export type GetRecommendationsRecommendGetResponses = {
    /**
     * Successful Response
     */
    200: RecommendationResponse;
};

export type GetRecommendationsRecommendGetResponse = GetRecommendationsRecommendGetResponses[keyof GetRecommendationsRecommendGetResponses];
