// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * GameDetail
 *
 * Full game detail for /games/{app_id}.
 */
export type GameDetail = {
    /**
     * App Id
     */
    app_id: number;
    /**
     * Game Name
     */
    game_name: string;
    /**
     * Header Image
     */
    header_image: string | null;
    /**
     * Short Description
     */
    short_description: string;
    /**
     * Genres
     */
    genres: Array<string>;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Screenshots
     */
    screenshots: Array<string> | null;
    /**
     * Wilson Score
     */
    wilson_score: number;
    /**
     * Other Players Also Played
     */
    other_players_also_played: Array<GameRecommendation> | null;
};

/**
 * GameRecommendation
 *
 * A single recommended game.
 */
export type GameRecommendation = {
    /**
     * App Id
     */
    app_id: number;
    /**
     * Game Name
     */
    game_name: string;
    /**
     * Header Image
     */
    header_image: string | null;
    /**
     * Hybrid Score
     */
    hybrid_score: number;
};

/**
 * GameSearchResult
 *
 * Search result.
 */
export type GameSearchResult = {
    /**
     * App Id
     */
    app_id: number;
    /**
     * Game Name
     */
    game_name: string;
};

/**
 * GameTagResult
 *
 * Result for a single tag search.
 */
export type GameTagResult = {
    /**
     * App Id
     */
    app_id: number;
    /**
     * Game Name
     */
    game_name: string;
    /**
     * Header Image
     */
    header_image: string | null;
    /**
     * Tags
     */
    tags: Array<string>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PlayedGameResponse
 *
 * A game played by a user fetched from Steam.
 */
export type PlayedGameResponse = {
    /**
     * App Id
     */
    app_id: number;
    /**
     * Game Name
     */
    game_name: string;
    /**
     * Hours
     */
    hours: number;
};

/**
 * ProfileRecommendationResponse
 *
 * Response wrapper for the /recommend/profile endpoint.
 */
export type ProfileRecommendationResponse = {
    /**
     * Recommendations
     */
    recommendations: Array<GameRecommendation>;
};

/**
 * ProfileRequest
 *
 * Request body for the /recommend/profile endpoint.
 */
export type ProfileRequest = {
    /**
     * App Ids
     */
    app_ids: Array<number>;
    /**
     * Hours Played
     */
    hours_played: Array<number>;
    /**
     * Top N
     */
    top_n: number;
};

/**
 * RecommendationResponse
 *
 * Response wrapper for the /recommend endpoint.
 */
export type RecommendationResponse = {
    /**
     * Target Game
     */
    target_game: string;
    /**
     * Recommendations
     */
    recommendations: Array<GameRecommendation>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type SearchGamesGamesSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         *
         * Search query
         */
        q: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/games/search';
};

export type SearchGamesGamesSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchGamesGamesSearchGetError = SearchGamesGamesSearchGetErrors[keyof SearchGamesGamesSearchGetErrors];

export type SearchGamesGamesSearchGetResponses = {
    /**
     * Response Search Games Games Search Get
     *
     * Successful Response
     */
    200: Array<GameSearchResult>;
};

export type SearchGamesGamesSearchGetResponse = SearchGamesGamesSearchGetResponses[keyof SearchGamesGamesSearchGetResponses];

export type SearchTagsGamesTagsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         *
         * Search query
         */
        q: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/games/tags';
};

export type SearchTagsGamesTagsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchTagsGamesTagsGetError = SearchTagsGamesTagsGetErrors[keyof SearchTagsGamesTagsGetErrors];

export type SearchTagsGamesTagsGetResponses = {
    /**
     * Response Search Tags Games Tags Get
     *
     * Successful Response
     */
    200: Array<string>;
};

export type SearchTagsGamesTagsGetResponse = SearchTagsGamesTagsGetResponses[keyof SearchTagsGamesTagsGetResponses];

export type SearchGamesByTagsGamesByTagsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Tags
         *
         * Tags to filter by
         */
        tags: Array<string>;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         *
         * Number of results to skip
         */
        offset?: number;
    };
    url: '/games/by-tags';
};

export type SearchGamesByTagsGamesByTagsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchGamesByTagsGamesByTagsGetError = SearchGamesByTagsGamesByTagsGetErrors[keyof SearchGamesByTagsGamesByTagsGetErrors];

export type SearchGamesByTagsGamesByTagsGetResponses = {
    /**
     * Response Search Games By Tags Games By Tags Get
     *
     * Successful Response
     */
    200: Array<GameTagResult>;
};

export type SearchGamesByTagsGamesByTagsGetResponse = SearchGamesByTagsGamesByTagsGetResponses[keyof SearchGamesByTagsGamesByTagsGetResponses];

export type GetGameGamesAppIdGetData = {
    body?: never;
    path: {
        /**
         * App Id
         */
        app_id: number;
    };
    query?: never;
    url: '/games/{app_id}';
};

export type GetGameGamesAppIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGameGamesAppIdGetError = GetGameGamesAppIdGetErrors[keyof GetGameGamesAppIdGetErrors];

export type GetGameGamesAppIdGetResponses = {
    /**
     * Successful Response
     */
    200: GameDetail;
};

export type GetGameGamesAppIdGetResponse = GetGameGamesAppIdGetResponses[keyof GetGameGamesAppIdGetResponses];

export type GetRecommendationsRecommendGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Game
         *
         * Name of the game to find recommendations for
         */
        game: string;
        /**
         * Top N
         *
         * Number of recommendations
         */
        top_n?: number;
        /**
         * Quality Power
         *
         * Quality weight exponent
         */
        quality_power?: number;
    };
    url: '/recommend';
};

export type GetRecommendationsRecommendGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRecommendationsRecommendGetError = GetRecommendationsRecommendGetErrors[keyof GetRecommendationsRecommendGetErrors];

export type GetRecommendationsRecommendGetResponses = {
    /**
     * Successful Response
     */
    200: RecommendationResponse;
};

export type GetRecommendationsRecommendGetResponse = GetRecommendationsRecommendGetResponses[keyof GetRecommendationsRecommendGetResponses];

export type GetProfileRecommendationsRecommendProfilePostData = {
    body: ProfileRequest;
    path?: never;
    query?: never;
    url: '/recommend/profile';
};

export type GetProfileRecommendationsRecommendProfilePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProfileRecommendationsRecommendProfilePostError = GetProfileRecommendationsRecommendProfilePostErrors[keyof GetProfileRecommendationsRecommendProfilePostErrors];

export type GetProfileRecommendationsRecommendProfilePostResponses = {
    /**
     * Successful Response
     */
    200: ProfileRecommendationResponse;
};

export type GetProfileRecommendationsRecommendProfilePostResponse = GetProfileRecommendationsRecommendProfilePostResponses[keyof GetProfileRecommendationsRecommendProfilePostResponses];

export type GetLibrarySteamLibrarySteamIdGetData = {
    body?: never;
    path: {
        /**
         * Steam Id
         *
         * Steam user ID
         */
        steam_id: string;
    };
    query?: never;
    url: '/steam/library/{steam_id}';
};

export type GetLibrarySteamLibrarySteamIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLibrarySteamLibrarySteamIdGetError = GetLibrarySteamLibrarySteamIdGetErrors[keyof GetLibrarySteamLibrarySteamIdGetErrors];

export type GetLibrarySteamLibrarySteamIdGetResponses = {
    /**
     * Response Get Library Steam Library  Steam Id  Get
     *
     * Successful Response
     */
    200: Array<PlayedGameResponse>;
};

export type GetLibrarySteamLibrarySteamIdGetResponse = GetLibrarySteamLibrarySteamIdGetResponses[keyof GetLibrarySteamLibrarySteamIdGetResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
